# Generated by Django 4.2.16 on 2024-12-04 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0002_productdetail_productkeyword_productdetailimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productdetail",
            name="detail_image",
        ),
    ]
