# Generated by Django 4.2.16 on 2024-12-04 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_remove_productdetail_detail_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdetail",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="product.product",
            ),
        ),
    ]
