# Generated by Django 4.2.16 on 2024-12-04 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_alter_productdetailimage_product_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductDetailImage",
            new_name="ProductImage",
        ),
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
    ]
