# Generated by Django 4.2.16 on 2024-12-05 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_rename_productdetailimage_productimage_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdetail",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="detailDescription",
                to="product.product",
            ),
        ),
    ]
