# Generated by Django 4.2.16 on 2024-12-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_productcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcomment",
            name="username",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
