# Generated by Django 4.2.16 on 2024-12-08 10:14

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_productcomment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdetail",
            name="detail_description",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
    ]
