# Generated by Django 5.1.3 on 2024-11-17 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("myapp", "0002_profile"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Profile",
        ),
    ]
